/**
 * @file autoGraphs.ts — auto-generate default bet-graphs from templates
 * when a mode is created or when a mode has trackables but no graphs.
 * @implements REQ-MODE-007
 */
import type { Trackable } from '../db/schema';
import { createBetGraph, listByMode } from '../repos/betGraphs';
import { buildGraph, type TemplateId } from '$lib/graph/templates';

/**
 * Generate one "Champion" (most events) bet-graph per entity-scoped trackable.
 * Only runs if the mode currently has 0 bet-graphs.
 */
export async function autoGenerateDefaultGraphs(
	modeId: string,
	trackables: Trackable[]
): Promise<number> {
	if (trackables.length === 0) return 0;

	// Don't overwrite existing graphs
	const existing = await listByMode(modeId);
	if (existing.length > 0) return 0;

	// Pick entity-scoped trackables (champion/loser needs entity scope);
	// fall back to all trackables if none are entity-scoped.
	let candidates = trackables.filter((t) => t.scope === 'entity');
	if (candidates.length === 0) candidates = trackables;

	const TEMPLATES_TO_GENERATE: { tpl: TemplateId; nameSuffix: string }[] = [
		{ tpl: 'champion', nameSuffix: 'Champion' }
	];

	let created = 0;
	for (const t of candidates) {
		for (const { tpl, nameSuffix } of TEMPLATES_TO_GENERATE) {
			const built = buildGraph(
				tpl,
				{ trackable: t.id },
				{ trackable: t.label }
			);
			if (!built.ok) continue;
			await createBetGraph({
				modeId,
				name: built.name || `${t.label} — ${nameSuffix}`,
				description: null,
				graphJson: built.graph,
				orderIndex: created
			});
			created++;
		}
	}
	return created;
}
